### ISSUE TITLE
Fail installation due to rlang

### ISSUE THREAD

**Issue by arianccbasile** [SysBioChalmers/FALCONET#34]
Dear Hongzhong,
I am trying to install your nice package with the provided instructions but it exits with the following error. 
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called ‘rlang’

I also tried to manually install "rlang" and it succeeds but it still gives me that error when I try to install FALCONET. 
Could you please help me with that? 

Sincerely,
Arianna Basile

**Comment by hongzhonglu** [comment]
Hi Arianna,
I just test the followed codes, it is OK on my mac. Could you share me your installing script?
install.packages("devtools")
devtools::install_github("SysBioChalmers/FALCONET")
